name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

env:
  PACKAGE_NAME: "pyterp"

jobs:
  details:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Extract tag name from Git ref
        id: release
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

  check_pypi:
    needs: details
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest version from PyPI
        id: pypi
        run: |
          LATEST_PYPI_VERSION=$(curl -s "https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json" | jq -r ".info.version" || echo "0.0.0")
          if [ "$LATEST_PYPI_VERSION" == "null" ]; then
            LATEST_PYPI_VERSION="0.0.0"
          fi
          echo "latest_pypi_version=$LATEST_PYPI_VERSION" >> "$GITHUB_OUTPUT"
          echo "Latest version on PyPI is $LATEST_PYPI_VERSION"

      - name: Compare new tag with PyPI version
        run: |
          NEW_TAG="${{ needs.details.outputs.tag_name }}"
          LATEST_PYPI_VERSION="${{ steps.pypi.outputs.latest_pypi_version }}"
          
          # Compara as versões (sort -V lida com semver)
          if [ "$(printf '%s\n' "$LATEST_PYPI_VERSION" "$NEW_TAG" | sort -rV | head -n 1)" != "$NEW_TAG" ] || [ "$NEW_TAG" == "$LATEST_PYPI_VERSION" ]; then
            echo "::error::New tag '${NEW_TAG}' is not greater than the latest PyPI version '${LATEST_PYPI_VERSION}'."
            exit 1
          else
            echo "New tag '${NEW_TAG}' is valid and greater than PyPI version '${LATEST_PYPI_VERSION}'."
          fi

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: [details, check_pypi]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build wheels with INTENSE DEBUGGING
        uses: pypa/cibuildwheel@v2.19.2
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: ${{ needs.details.outputs.tag_name }}
          
          CIBW_BEFORE_BUILD: >
            bash -c "
              set -euxo pipefail
              
              echo '--- PASSO 1: VERIFICANDO O AMBIENTE DENTRO DO CONTAINER ---'
              echo 'A tag recebida do workflow é: ${{ needs.details.outputs.tag_name }}'
              echo 'A variável de ambiente SETUPTOOLS_SCM_PRETEND_VERSION está definida como:'
              printenv | grep SETUPTOOLS_SCM_PRETEND_VERSION

              echo '--- PASSO 2: FORÇANDO A VERSÃO NO pyproject.toml ---'
              # Usamos `sed` para substituir a configuração dinâmica por uma versão fixa
              # O caminho /project é onde o cibuildwheel monta seu código
              sed -i 's/dynamic\s*=\s*\["version"\]/version = \"${{ needs.details.outputs.tag_name }}\"/' /project/pyproject.toml
              
              # Também removemos o setuptools-scm das dependências de build para ter certeza
              sed -i '/"setuptools-scm"/d' /project/pyproject.toml

              echo '--- Conteúdo do pyproject.toml MODIFICADO: ---'
              cat /project/pyproject.toml
              echo '---------------------------------------------'
            "
          
          CIBW_BEFORE_BUILD_LINUX: >
            bash -c "
              set -euxo pipefail;
              if command -v yum; then yum install -y libgomp;
              elif command -v dnf; then dnf install -y libgomp;
              elif command -v apt-get; then apt-get update && apt-get install -y --no-install-recommends libgomp1;
              fi
            "
          CIBW_SKIP: "*-musllinux* pp* *_i686"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: ./wheelhouse

  pypi_publish:
    name: Upload release to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/pyterp/
    permissions:
      id-token: write
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github_release:
    name: Create GitHub Release
    needs: [pypi_publish, details]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ needs.details.outputs.tag_name }}" dist/* \
            --title "${{ env.PACKAGE_NAME }} ${{ needs.details.outputs.tag_name }}" \
            --generate-notes