name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

env:
  PACKAGE_NAME: "pyterp"

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.verify_versions.outputs.version }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Verificar se tag e _version.py coincidem
        id: verify_versions
        run: |
          TAG_NAME="${{ github.ref_name }}"

          VERSION_FROM_TAG="${TAG_NAME#v}"
          
          VERSION_FROM_FILE=$(python -c "from src._version import __version__; print(__version__)")

          echo "Versão da Tag: ${VERSION_FROM_TAG}"
          echo "Versão do Arquivo: ${VERSION_FROM_FILE}"

          if [ "${VERSION_FROM_TAG}" != "${VERSION_FROM_FILE}" ]; then
            echo "::error::Erro: A versão da tag Git ('${VERSION_FROM_TAG}') não é a mesma da versão no _version.py ('${VERSION_FROM_FILE}')!"
            exit 1
          fi

          echo "As versões coincidem. Prosseguindo com a versão ${VERSION_FROM_TAG}"
          echo "version=${VERSION_FROM_TAG}" >> "$GITHUB_OUTPUT"

  check_pypi:
    needs: get_version
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest version from PyPI
        id: pypi
        run: |
          LATEST_PYPI_VERSION=$(curl -s "https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json" | jq -r ".info.version" || echo "0.0.0")
          if [ "$LATEST_PYPI_VERSION" == "null" ]; then
            LATEST_PYPI_VERSION="0.0.0"
          fi
          echo "latest_pypi_version=$LATEST_PYPI_VERSION" >> "$GITHUB_OUTPUT"
          echo "Latest version on PyPI is $LATEST_PYPI_VERSION"

      - name: Compare new tag with PyPI version
        run: |
          NEW_TAG="${{ needs.get_version.outputs.version }}"
          LATEST_PYPI_VERSION="${{ steps.pypi.outputs.latest_pypi_version }}"
          
          if [ "$(printf '%s\n' "$LATEST_PYPI_VERSION" "$NEW_TAG" | sort -rV | head -n 1)" != "$NEW_TAG" ] || [ "$NEW_TAG" == "$LATEST_PYPI_VERSION" ]; then
            echo "::error::New tag '${NEW_TAG}' is not greater than the latest PyPI version '${LATEST_PYPI_VERSION}'."
            exit 1
          else
            echo "New tag '${NEW_TAG}' is valid and greater than PyPI version '${LATEST_PYPI_VERSION}'."
          fi

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: [get_version, check_pypi]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Build wheels com cibuildwheel
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_BEFORE_BUILD_LINUX: >
            bash -c "
              set -euxo pipefail
              echo '--- Instalando dependências do Linux ---'
              if command -v yum; then yum install -y libgomp;
              elif command -v dnf; then dnf install -y libgomp;
              elif command -v apt-get; then apt-get update && apt-get install -y --no-install-recommends libgomp1;
              fi
            "
          
          CIBW_SKIP: "*-musllinux* pp* *_i686"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: ./wheelhouse

  pypi_publish:
    name: Upload release to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/pyterp/
    permissions:
      id-token: write
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github_release:
    name: Create GitHub Release
    needs: [pypi_publish, get_version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ needs.get_version.outputs.version }}
        run: |
          gh release create "${{ github.ref_name }}" dist/* \
            --title "${{ env.PACKAGE_NAME }} ${{ env.VERSION }}" \
            --generate-notes